### ISSUE TITLE
Release Code

### ISSUE THREAD

**Issue by 863689877** [haofeixu/gmflow#1]
When will the code be released?

**Comment by haofeixu** [comment]
Hi @863689877 , I am working on the code release and the camera-ready version of our paper, and will update the paper on arxiv and release the code before March 28, thanks.

**Comment by Shimmer93** [comment]
Will the code be released soon? I'm quite curious about your work.

**Comment by haofeixu** [comment]
Hi @Shimmer93 , thank you for your interest in our work!
I am almostly done with the code cleaning and are doing some testing currently. Hopefully the code will be released in one day or two. I have already updated our paper on arxiv (https://arxiv.org/abs/2111.13680) and more analysis is included. Thanks!

**Comment by haofeixu** [comment]
Hi @863689877 @Shimmer93 , the code and models have been released.

**Comment by Shimmer93** [comment]
> Hi @863689877 @Shimmer93 , the code and models have been released.

Thank you! I think the issue can be closed now.
