### ISSUE TITLE
关于训练策略

### ISSUE THREAD

**Issue by klinic** [haofeixu/gmflow#10]
大佬您好

我想向您请教一下

【1】您的训练流程是不是和train_gmflow.sh或train_gmflow_with_refine.sh一样：先在chairs上训练，然后在Things上微调，然后在sintel上微调，然后在kitti上微调。这4个数据集都需要跑一遍，而且是一环扣一环呢？

【2】这4个数据集都跑一遍（在4张V100上）需要多长时间呢？我目前的设备是5张3090

祝好！！！

**Comment by haofeixu** [comment]
Hi 您好，

[1] 是的，是按我们 .sh 文件里提供的顺序训练
[2] train_gmflow.sh 应该需要三天左右，train_gmflow_with_refine.sh 会更长一些

祝好！

**Comment by klinic** [comment]
谢谢您的答疑
