### ISSUE TITLE
不支持直接推理视频流

### ISSUE THREAD

**Issue by AlanLi1997** [haofeixu/gmflow#11]
您好，感谢您慷慨地将此工作设置为开放获取。

我发现目前的版本似乎不支持直接对视频流进行推理。我不得不 video2images + Img2Video 后来获得视频流的光流结果。
如果能增加对视频流的实时推理将更好(这对GMFlow似乎是有难度的)。我在RTX3060上对651张图片进行了推理，耗时420.8246901035309秒。FlowNet2似乎能做到实时(从他们的演示视频上来看)。

这只是一个友好的建议，感谢将该工作开源。

**Comment by haofeixu** [comment]
Hi 您好，很好的建议，后续会考虑添加这一功能，感谢。

关于时间，不带 refine 的 GMFlow 模型对 sintel 分辨率图片单张推理 时间在 57ms 左右，更多速度上的分析可见我们论文。祝好。

**Comment by haofeixu** [comment]
Hi @AlanLi1997 , 直接推理视频流已在我们的最新代码中支持，可见：https://github.com/autonomousvision/unimatch . 也可以直接在 colab 尝试使用：https://colab.research.google.com/drive/1r5m-xVy3Kw60U-m5VB-aQ98oqqg_6cab?usp=sharing
