### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by menghuaa** [haofeixu/gmflow#12]
您好，gmflow提取特征时会降低图片分辨率，得到预测的光流后，会将光流进行上采样回到原始大小。我想问一下，gmflow能否不降低图片的分辨率提取特征，然后进行相似度计算呢？

**Comment by menghuaa** [comment]
进行convex upsampling时，为什么要输入feature0 和 flow 得到mask呢？为什么不只输入feature0

**Comment by haofeixu** [comment]
> 您好，gmflow提取特征时会降低图片分辨率，得到预测的光流后，会将光流进行上采样回到原始大小。我想问一下，gmflow能否不降低图片的分辨率提取特征，然后进行相似度计算呢？

您好，理论上是可以的，只是实际中分辨率过高的时候计算量也会增加。当图片分辨率较低或者对计算量没有要求的时候，可以尝试使用更高的特征分辨率 (e.g., 1/4 or 1/2)，甚至原图。

**Comment by haofeixu** [comment]
> 进行convex upsampling时，为什么要输入feature0 和 flow 得到mask呢？为什么不只输入feature0

最终上采样之后的 flow 是用学到的 mask 对 flow 做加权平均，实验中发现让 mask 的预测与 flow 相关有更好的效果，所以将 flow 也作为 mask 的输入。
