### ISSUE TITLE
How to modify  gmflow  for stereo matching task

### ISSUE THREAD

**Issue by excllent123** [haofeixu/gmflow#13]
Hi  

I  want to modify gmflow  for stereo matching task  like RAFT and RAFT-stereo， can you give me some advices?

Thanks

**Comment by haofeixu** [comment]
Hi,

Adapting GMFlow to stereo matching is simple, just need to replace the 2D cross-attention in Transformer with 1D cross-attention, and replace the 2D global matching with 1D global matching.

Thanks

**Comment by excllent123** [comment]
Hi   haofei,
      首先感谢您的快速回复
      也就是说修改global-correction-softmax  以及FeatureFlowAttention ，将x/y方向的匹配修改为X方向的匹配？
     
Thanks

**Comment by haofeixu** [comment]
> Hi haofei, 首先感谢您的快速回复 也就是说修改global-correction-softmax 以及FeatureFlowAttention ，将x/y方向的匹配修改为X方向的匹配？
> 
> Thanks

是的。

**Comment by haofeixu** [comment]
Hi @excllent123 , I have released the details and code regarding how to modify GMFlow to stereo, you can find more info at https://haofeixu.github.io/unimatch/ and https://github.com/autonomousvision/unimatch, thanks.
