### ISSUE TITLE
pretrained model not found

### ISSUE THREAD

**Issue by sirlancer** [haofeixu/gmflow#14]
你好，预训练好的模型下载不了了，链接失效了，麻烦给个最新的链接呗，感谢！

**Comment by haofeixu** [comment]
你好，我这边看了下 google drive 链接是没问题的，可以正常下载，要不你再试下？祝好~

**Comment by sirlancer** [comment]
> 你好，我这边看了下 google drive 链接是没问题的，可以正常下载，要不你再试下？祝好~
我这边可以看到google drive里面的压缩包，但是一点下载就无法访问了，可能是网的原因，能否给个国内的链接呢？感谢~

**Comment by haofeixu** [comment]
链接：https://pan.baidu.com/s/1fziqApxZpvGmPuevfd1izQ 
提取码：ejvo
