### ISSUE TITLE
about feature extraction

### ISSUE THREAD

**Issue by menghuaa** [haofeixu/gmflow#15]
您好，对于图片的特征提取，使用backbone.py里的CNNEncoder提取特征，是可以实现单独输入一张图片提取特征是吗？
对于使用transformer来增强特征，是必须在一对图片的基础上提取特征吗？如果仅输入一张图片提取transformer的特征，在您这里是不允许对吗？

**Comment by haofeixu** [comment]
对单张图片提取特征也是没问题的，只需要去掉 cross-attention 部分即可。
