### ISSUE TITLE
Inquery about how to refine on higher resolution.

### ISSUE THREAD

**Issue by Magicboomliu** [haofeixu/gmflow#16]
Firstly, Thank you for your outstanding work. I benefit a lot.

I have some issues with the strategy of refining on higher resolution.

It is firstly trained on the lower resolution and obtains a pre-trained model. Is it then using the pre-trained model as the initial weight to predict the residual on higher resolution? (I mean trained again and again, from 1/8 scale to 1/4 scale to 1/2 scale then to full scale).

Does it mean that if I want to refine fully, I must refine 3 times (train extra 3 times)for refining at the highest resolution?

Looking forward to your reply.

**Comment by haofeixu** [comment]
Hi @Magicboomliu , thank you for your kind words!

The model with refinement (1/8 & 1/4) in our paper can be trained from random initialization, without requiring to train the 1/8 model first, as shown in our training scripts: https://github.com/haofeixu/gmflow/blob/main/scripts/train_gmflow_with_refine.sh

Thanks.
