### ISSUE TITLE
关于相似度矩阵

### ISSUE THREAD

**Issue by menghuaa** [haofeixu/gmflow#17]
您好，您在计算相似度矩阵时是直接将特征向量进行点积运算得到相似性矩阵。我把特征向量进行了归一化处理（每个像素点特征向量的模归一化为1），然后将归一化后的特征向量进行点积运算得到相似性矩阵，相似性矩阵没有再除以c**0.5。理论上这样处理应该是可行的呀，特征之间计算相似度去除了特征向量本身长度的影响。但是我这样处理后，loss降不下去。请问您有什么建议吗？或者说我这样处理本身就不对吗？

**Comment by menghuaa** [comment]
> 您好，这种计算方式理论上也能描述相似度，或许实际中会带来一些潜在的优化上的问题？不过我也没有尝试过。

@haofeixu 您好，我还想问下为什么模型中的cnn提取特征会占那么大显存呢？训练时我输入2张336*336的图片，我把提取cnn特征时改为降采样1/2，nvidia-smi显示提取cnn特征前占用1591MB，提取特征后占用12497MB，为什么会占用这么大显存呢？有什么让cnn更轻量级又不会太降低性能的方法嘛

**Comment by haofeixu** [comment]
您好，应该是高分辨率导致 Transformer 部分计算量增加造成的。

**Comment by menghuaa** [comment]
> 您好，应该是高分辨率导致 Transformer 部分计算量增加造成的。

并不是呢，已经把transformer结构注释掉了，仅仅cnn就占了那么多
