### ISSUE TITLE
Questions about the data

### ISSUE THREAD

**Issue by 863689877** [haofeixu/gmflow#2]
Hi, I'm confused about the **1.89** in Table 2d and **1.65** in Table 2e in your paper. I think they should be the same. Could you explain their difference?

**Comment by haofeixu** [comment]
Hi @863689877 , the difference lies in the **upsampling** method. 

To make the comparisons as specific as possible, we use the simple **bilinear** upsampling for all methods in Table 2a-2d and also Table 1. You can find the relevant description in Section 4.1 (bottom right of page 5): ``Both methods
use bilinear upsampling in this comparison".
After Table 2e, all experimets are using the learned **convex** upsampling for the system-level comparisons. That is, the improvement from 1.89 to 1.65 comes from the learned upsampling module.

Besides, for ablation experiments, we train on Things for 200K iterations for fast experiments; while our final model is trained for 800K iterations (mentioned in Section 4 implementation details). Hope this can make it clear for the difference in Table 2e and Table 3 (w/o refinement) models (200K vs. 800K).

**Comment by 863689877** [comment]
Thank you for your patient answer. Now I understand it.
