### ISSUE TITLE
About extension in Sintel leaderboard

### ISSUE THREAD

**Issue by Euiyeon-Kim** [haofeixu/gmflow#20]
First I must appreciate that you opened public code for your novel work.

I have a question about your score on the official MPISintel leaderboard.

According to an official paper published in CVPR2022, 
GMFlow's AEPE for Sintel clean and final test set was 1.74 and 2.90
but in the official leaderboard, GMFlow+'s AEPE is 1.028 and 2.367 for Sintel clean and final test set.

Can you tell me which extension added for GMFlow leads to such extreme performance improvement?

**Comment by haofeixu** [comment]
Thanks for your kind words.

Basically, we use additional post-processing steps to further improve the performance. I will release the code and models in the near future, thanks.

**Comment by haofeixu** [comment]
Hi @Euiyeon-Kim , I have released our improved GMFlow model at https://github.com/autonomousvision/unimatch, and more info about our new work can be found at at https://haofeixu.github.io/unimatch/. Hope it helps, thanks.
