### ISSUE TITLE
about backward flow

### ISSUE THREAD

**Issue by newtreeaa** [haofeixu/gmflow#21]
大佬您好，请问给出frame0、frame1。前向光流：frame0->frame1的光流，frame0每个像素的坐标加上前向光流值得到每个像素在frame1中的坐标。大佬能用这样的描述方式，给我描述下后向光流嘛？我搞不懂后向光流，资料也查不到

**Comment by haofeixu** [comment]
您好，backward flow 顾名思义就是指 frame1 -> frame0 的光流，即 frame1每个像素的坐标加上backward flow 值得到每个像素在frame0中的坐标
