### ISSUE TITLE
about evaluation padding

### ISSUE THREAD

**Issue by spicy-dog** [haofeixu/gmflow#22]
Nice work, congratulations!
I notice that the crop size of image in gmflow training is totally different with raft, and I wonder how you set that parameter. Besides, during evaluation, padding size of gmflow is greater than raft, will it affect the final performance of gmflow? 
Looking forward to your reply.

**Comment by haofeixu** [comment]
Thanks. The crop size should be divisiable by 16 or 32 in our model due to the split window attention operation, and we choose the crop size emprically to meet this requirement. Similar reason for the padding size.

**Comment by spicy-dog** [comment]
您好，您的邮件我已经收到了，谢谢
