### ISSUE TITLE
Reproducing results for KITTI 

### ISSUE THREAD

**Issue by SunghwanHong** [haofeixu/gmflow#24]
Hi.

Thanks for the nice work! 
I'm trying to reproduce the results for KITTI dataset reported in Table 4.
Can you please tell me which pretrained weights and the hyperparameters I should use in order to obtain the best results?

Also, I'm planning to evaluate GMFlow on HPatches and ETH3D as well. 
For this, can you tell me , in order to obtain the best results, which weights and hyperparameters  I should select? 

I will be waiting for your reply! 
Thanks!

**Comment by haofeixu** [comment]
Hi, 

Thanks for your kind words!

To reproduce the results (training data C+T) in Table 4, you should use the `gmflow_with_refine_things-36579974.pth` model. If you also need the model that is trained on the additional Virtual KITTI2 dataset (C+T+VK), please let me know.

This script should reproduce these numbers:
```
python main.py \
--eval \
--resume pretrained/gmflow_with_refine_things-36579974.pth \
--val_dataset kitti \
--with_speed_metric \
--padding_factor 32 \
--upsample_factor 4 \
--num_scales 2 \
--attn_splits_list 2 8 \
--corr_radius_list -1 4 \
--prop_radius_list -1 1 \
--with_speed_metric
```

To evaluate on HPatches and ETH3D, I would suggest you to try the Sintel model `gmflow_with_refine_sintel-3ed1cf48.pth`,  and here is script for inference: https://github.com/haofeixu/gmflow/blob/main/scripts/demo.sh#L42-L51

Hope it helps.

Thanks!

**Comment by SunghwanHong** [comment]
Wow. Thanks for the quick reply! 
This definitely helps and will save a lot of time for me! 

I will try them and come back with the results.
I want to confirm that the results I obtain are reasonable to you.

**Comment by SunghwanHong** [comment]
Hi, 
Now I'm ready to evaluate GMFlow on HPatches and ETH3D. 
I've tried evaluating on HPatches 240 and I obtained EPE of :
scene 1 : 5.441167
scene 2 : 9.663044
scene 3 : 17.886573
scene 4 : 20.688895
scene 5 : 33.432529
ALL : 17.422442

The results may not seem so good, but this sounds reasonable, since the weights are from training on SINTEL. 
Does this look okay to you?

One issue is that when I'm trying to evaluate on original HPatches and ETH3D, memory explodes (I'm using 3090).
So I'm planning to downsample the input image pairs, process them, then evaluate at original size by upsampling back. 
Do you suggest any specific image resolution sizes? Because if I adjust to the same image size as your training setup, i would get the best results. 

Thanks!

**Comment by haofeixu** [comment]
May I know the original image resolution on HPatches and the inference resolution you used to obtain these numbers? Thanks!

**Comment by SunghwanHong** [comment]
Oh the results are obtained by resizing the images to 240x240. 

The original resolution of HPatches range from 450x600 to 1613x1210.

**Comment by SunghwanHong** [comment]
The results I provided at first are obtained by resizing the images to 240x240, processing them to obtain flow map of size 240x240 and computing EPE using the GT flow defined at 240x240. This is what previous works used to do a few years ago. Nowadays, we evaluate the methods using the GT flow defined at the original resolution, which ranges from 450x600 to 1613x1210. So it is quite natural to observe higher EPEs. 

As an additional information, the higher scene in HPatches consists of more difficult images with larger geometric deformations in general. 

Please let me know if I correctly addressed your question! 
Thanks!

**Comment by SunghwanHong** [comment]
The results I provided at first are obtained by resizing the images to 240x240, processing them to obtain flow map of size 240x240 and computing EPE using the GT flow defined at 240x240. This is what previous works used to do a few years ago. Nowadays, we evaluate the methods using the GT flow defined at the original resolution, which ranges from 450x600 to 1613x1210. So it is quite natural to observe higher EPEs. 

As an additional information, the higher scene in HPatches consists of more difficult images with larger geometric deformations in general. 

Please let me know if I correctly addressed your question!

**Comment by SunghwanHong** [comment]
The results I provided at first are obtained by resizing the images to 240x240, processing them to obtain flow map of size 240x240 and computing EPE using the GT flow defined at 240x240. This is what previous works used to do a few years ago. Nowadays, we evaluate the methods using the GT flow defined at the original resolution, which ranges from 450x600 to 1613x1210. So it is quite natural to observe higher EPEs. 

As an additional information, the higher scene in HPatches consists of more difficult images with larger geometric deformations in general. 

Please let me know if I correctly addressed your question!

**Comment by SunghwanHong** [comment]
The results I provided at first are obtained by resizing the images to 240x240, processing them to obtain flow map of size 240x240 and computing EPE using the GT flow defined at 240x240. This is what previous works used to do a few years ago. Nowadays, we evaluate the methods using the GT flow defined at the original resolution, which ranges from 450x600 to 1613x1210. So it is quite natural to observe higher EPEs. 

As an additional information, the higher scene in HPatches consists of more difficult images with larger geometric deformations in general. 

Please let me know if I correctly addressed your question!

**Comment by SunghwanHong** [comment]
The results I provided at first are obtained by resizing the images to 240x240, processing them to obtain flow map of size 240x240 and computing EPE using the GT flow defined at 240x240. This is what previous works used to do a few years ago. Nowadays, we evaluate the methods using the GT flow defined at the original resolution, which ranges from 450x600 to 1613x1210. So it is quite natural to observe higher EPEs. 

As an additional information, the higher scene in HPatches consists of more difficult images with larger geometric deformations in general. 

Please let me know if I correctly addressed your question!

**Comment by haofeixu** [comment]
OK, I see. 

Clearly your inference resolution is too small to get good results. Our sintel model is trained with 320x896 resolution, thus I would suggest you to do inference on resolutions like that. This can be done by passing the parameter `--inference_size 320 896` in your command.

**Comment by SunghwanHong** [comment]
Okay, then I will resize the input images to 320x896 first, then feed them to the model, get the output flow, and resize back to original image sizes to compute EPE and compare with other methods in a fair comparison.

**Comment by haofeixu** [comment]
> The results I provided at first are obtained by resizing the images to 240x240, processing them to obtain flow map of size 240x240 and computing EPE using the GT flow defined at 240x240. This is what previous works used to do a few years ago. Nowadays, we evaluate the methods using the GT flow defined at the original resolution, which ranges from 450x600 to 1613x1210. So it is quite natural to observe higher EPEs.
> 
> As an additional information, the higher scene in HPatches consists of more difficult images with larger geometric deformations in general.
> 
> Please let me know if I correctly addressed your question!

That looks reasonable to me. So definitely you can use the results for comparison. Thanks!

**Comment by SunghwanHong** [comment]
Nice! I will close the comment. 
Thanks for your support!

**Comment by SunghwanHong** [comment]
Hi, 
I got the results:
HPatches Original 
Scene 1: 4.71576
Scene 2: 26.463095
Scene 3: 40.754662
Scene 4: 62.489922
Scene 5: 79.803975
ALL: 42.845846

ETH3D:
rate 3: 1.641432
rate 5: 1.861459
rate 7: 2.115843
rate 9: 2.360460
rate 11: 3.492452
rate 13: 5.615580
rate 15: 10.643543

It seems that for images (low rates and scenes of eth3d and hpatches) that are similar to optical flow datasets, GMFlow is excels (almost SOTA), but struggles when the geometric deformation gets more extreme. Are you good with the results?

**Comment by haofeixu** [comment]
Are the results on HPatches comparable with the one you provided before (https://github.com/haofeixu/gmflow/issues/24?notification_referrer_id=NT_kwDOAScoc7M0NzY2OTY3MTY2OjE5MzQzNDc1#issuecomment-1304737836)? Seems that the errors get larger (sorry that I haven't worked on HPatches dataset before).
