### ISSUE TITLE
how to generate onnx model with dynamic shapes

### ISSUE THREAD

**Issue by hermosayhl** [haofeixu/gmflow#26]
as stated in title.
I have tried to make it, only to find the transformer cannot be transformed to onnx with dynamic shapes

**Comment by haofeixu** [comment]
Hi, sorry that I didn't have too much experience on onnx, maybe you can try the solutions on google? https://www.google.com/search?q=generate+onnx+model+with+dynamic+shapes

**Comment by 98mxr** [comment]
May I ask if you solved this problem, I have a lot of difficulties trying to optimize GMFlow with tensorrt.

**Comment by haofeixu** [comment]
A workaround could be using fixed image resolution for inference. For example, you could try to resize the input images to a fixed resolution before feeding them to the network, and finally resize the flow prediction back to the original image resolution.

**Comment by longgekakaka** [comment]
> as stated in title. I have tried to make it, only to find the transformer cannot be transformed to onnx with dynamic shapes

你知道怎么讲模型转换乘接受固定大小的onnx模型吗?
