### ISSUE TITLE
About weight-sharing convolution with strides 1 and 2

### ISSUE THREAD

**Issue by dangnh0611** [haofeixu/gmflow#29]
Hi, from the paper:
"To generate the 1/4 and 1/8 features, we also share the backbone features. Specifically, we take a similar approach to TridentNet [23] but use a weight-sharing convolution with strides 1 and 2, respectively. Such a weight-sharing design also leads to better performance than the feature pyramid network [25].
"
Does it means 1/8 feature map is (equivalent to) a pooled version of 1/4 feature map (i.e fixed position pooling) ? Then 1/4 and 1/8 feature map share the same receptive field size ?
Thanks in advance!

**Comment by haofeixu** [comment]
Hi, I think they are not equivalent since the sampling locations of the convolutions are different.
