### ISSUE TITLE
flickering effect

### ISSUE THREAD

**Issue by emjay73** [haofeixu/gmflow#31]
Thank you for sharing the code!

I ran gmflow on some of the datasets from webvid-10M(https://maxbain.com/webvid-dataset/) using the pre-trained checkpoint named 'gmflow_sintel-0c07dcb3.pth'.

As we can see from the following videos, there are noticeable flickering artifacts.

https://github.com/haofeixu/gmflow/assets/36818801/f48738b3-1dba-4f25-91a1-e9dc25cf9e00

https://github.com/haofeixu/gmflow/assets/36818801/b3b021ce-e88a-47e7-a001-375822253f1a

https://github.com/haofeixu/gmflow/assets/36818801/292552c3-f7f2-4f34-a358-6652cb5f8405

Which pre-trained weight should I use for general videos such as webvid-10M?

And is there any suggested solution for the flickering effect?

Thank you in advance.

**Comment by haofeixu** [comment]
Maybe you can try this model: https://github.com/autonomousvision/unimatch/blob/master/scripts/gmflow_demo.sh#L7

**Comment by emjay73** [comment]
Thank you for the prompt reply!
I tried to replace the pretrained weight using the weight that you mentioned, but the output results do not coincide with the input images.
So I cloned the unimatch repo and ran the code using the following arguments.
```
--resume pretrained/gmflow-scale2-regrefine6-mixdata-train320x576-4e7b215d.pth \
--output_path output/gmflow-scale2-regrefine6-davis \
--padding_factor 32 \
--upsample_factor 4 \
--num_scales 2 \
--attn_splits_list 2 8 \
--corr_radius_list -1 4 \
--prop_radius_list -1 1 \
--reg_refine \
--num_reg_refine 6
```

The output results seem more reasonable, but I was not able to escape from the flickering artifact.


https://github.com/haofeixu/gmflow/assets/36818801/abe8de41-fa35-4211-8b70-81ed35388b7e


https://github.com/haofeixu/gmflow/assets/36818801/73c3ecbe-ca79-4a75-9162-606055a0755b


https://github.com/haofeixu/gmflow/assets/36818801/f586fbd4-6b2a-456a-aeed-3a6e386cc4a4


Are there any arguments that relate to the flickering effect that I can try out?

**Comment by haofeixu** [comment]
Hi I guess the flickering results are somewhat expected since the model is trained with two frames only, without any temporal consistency constraints.

**Comment by emjay73** [comment]
@haofeixu Thank you for your valuable opinion.
I was planning to utilize the results of the denseflow for the other task but did not know how it was supposed to behave.
I got a grasp of denseflow behavior thanks to you.
I'll close the issue.
