### ISSUE TITLE
reconstruct next frame via inferenced optical flow and png to flo

### ISSUE THREAD

**Issue by yi0109** [haofeixu/gmflow#33]
first of all, I would like to thank you for your excellent research sharing.
I am beginner to study related things.
It seems it convert optical flow to image by flow_viz
I want reproduce the next frame via optical flow image and prev frame to evaluate how accurate the optical flow is. How can I do that.?
I tried with opencv func calcOpticalFlowFarneback but I cant get proper result. 
Is there anyone who can help?

**Comment by yi0109** [comment]
many tasks seems predict next frame with prev frame and uv flow vector.

I want to know how to convert png to flo also.
how can I do that?

**Comment by haofeixu** [comment]
Thanks for your interest in our work. 
To save the .flo flow results, you can use the `save_flow_flo` argument: https://github.com/haofeixu/gmflow/blob/main/evaluate.py#L572

**Comment by yi0109** [comment]
Thanks for your reply.
1. is it possible warp from prev frame png and optical colormap png?
2. if it can't how to convert optical flow image to vector??
3. and how to make next frame from prev frame and optical flow.?
I need to eval custom dataset by compare next frame and generated next frame.

**Comment by yi0109** [comment]
Thanks for your reply 

I test flow_warp with sintel gt dataset but the result is a little bit weird.
Can you tell which part is the problem?  I've attached the result image and the flo file as a zip.
<prev frame>
![frame_0003](https://github.com/haofeixu/gmflow/assets/129710121/ac573ce7-2ad2-42f1-942a-3b4a0147d535)
<generated frame(warping)>
![output_image](https://github.com/haofeixu/gmflow/assets/129710121/0f826fad-54ad-4002-955c-dae185dcd7c7)
<expected frame(next frame)>
![frame_0004(expected result)](https://github.com/haofeixu/gmflow/assets/129710121/ef1e635e-5cee-4187-8744-9350b0f41e68)

```
from gmflow.geometry import flow_warp
from utils.frame_utils import readFlow


import cv2
import torch

prev_frame_path='sintel_dataset/training/clean/ambush_2/frame_0003.png'
next_frame_path='sintel_dataset/training/clean/ambush_2/frame_0004.png'
optical_path='sintel_dataset/training/flow/ambush_2/frame_0003.flo'


def convert_tensor_as_image(tensor):
    tensor = tensor.cpu()
    numpy_img = tensor.squeeze(0).numpy()
    if numpy_img.dtype != 'uint8':
        numpy_img = (numpy_img * 255).astype('uint8')

    if numpy_img.shape[-1] != 3:
        numpy_img = numpy_img.transpose(1, 2, 0)

    return numpy_img

def save_tensor_as_image(tensor, filename):
    numpy_img = convert_tensor_as_image(tensor)
    print(f"Saving image of shape {numpy_img.shape} and type {numpy_img.dtype}")
    cv2.imwrite(filename, numpy_img)


flow=readFlow(optical_path)
prev_frame=cv2.imread(prev_frame_path)
next_frame=cv2.imread(next_frame_path)
print(f'flow shape : {flow.shape}:{type(flow)}')
print(f'prev_frame shape : {prev_frame.shape}:{type(prev_frame)}')

flow_tensor = torch.from_numpy(flow).clone().detach().permute(2,0,1).unsqueeze(0)
prev_frame_tensor = torch.from_numpy(prev_frame).clone().detach().permute(2,0,1).unsqueeze(0).to(torch.float32)/255.0
print(f'prev_frame_tensor : {prev_frame_tensor.shape} : {prev_frame_tensor.dtype}')
print(f'flow_tensor : {flow_tensor.shape} : {flow_tensor.dtype}')
warp_result = flow_warp(prev_frame_tensor, flow_tensor)

print(f'warp_result : {warp_result.shape}')
numpy_img = convert_tensor_as_image(warp_result)
cv2.imwrite('output_image.jpg', numpy_img )
[frame_0003_flo.zip](https://github.com/haofeixu/gmflow/files/12436697/frame_0003_flo.zip)

cv2.imwrite('diff.jpg', next_frame - numpy_img )
```

**Comment by haofeixu** [comment]
The  warping operation is backward warping, which means you should use frame_0003.flo to warp frame_0004.png so that you can get a reconstructed frame_0003.png

**Comment by yi0109** [comment]
okay. I will try it again. is there api forward warping???
