### ISSUE TITLE
Conda env create fails

### ISSUE THREAD

**Issue by igor-kurenkov** [haofeixu/gmflow#36]
Windows 10. Cloned the repo, creating the env, same result with CONDA_RESTORE_FREE_CHANNEL=1 and CONDA_RESTORE_FREE_CHANNEL=0:

(base) PS E:\portable\gmflow> SET CONDA_RESTORE_FREE_CHANNEL=1
(base) PS E:\portable\gmflow> conda env create --name gmflow -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - tornado==6.1=py38h27cfd23_0
  - cudatoolkit==10.2.89=hfd86e86_1
  - libgfortran-ng==7.5.0=ha8ba4b0_17
  - libpng==1.6.37=hbc83047_0
  - libgomp==9.3.0=h5101ec6_17
  - libffi==3.3=he6710b0_2
  - xz==5.2.5=h7b6447c_0
  - lcms2==2.12=h3be6417_0
  - libiconv==1.15=h63c8f33_5
  - mkl_fft==1.3.0=py38h42c9631_2
  - glib==2.69.0=h5202010_0
  - ninja==1.10.2=hff7bd54_1
  - mkl-service==2.4.0=py38h7f8727e_0
  - zstd==1.4.9=haebb681_0
  - libxcb==1.14=h7b6447c_0
  - numpy==1.20.3=py38hf144106_0
  - openssl==1.1.1m=h7f8727e_0
  - sip==4.19.13=py38he6710b0_0
  - libxml2==2.9.12=h03d6c58_0
  - libidn2==2.3.2=h7f8727e_0
  - libuuid==1.0.3=h1bed415_2
  - kiwisolver==1.3.1=py38h2531618_0
  - pcre==8.45=h295c915_0
  - _openmp_mutex==4.5=1_gnu
  - sqlite==3.36.0=hc218d9a_0
  - libunistring==0.9.10=h27cfd23_0
  - expat==2.4.1=h2531618_2
  - zlib==1.2.11=h7b6447c_3
  - readline==8.1=h27cfd23_0
  - intel-openmp==2021.3.0=h06a4308_3350
  - libgfortran4==7.5.0=ha8ba4b0_17
  - gnutls==3.6.15=he1e5248_0
  - lz4-c==1.9.3=h2531618_0
  - brotli==1.0.9=he6710b0_2
  - libwebp-base==1.2.0=h27cfd23_0
  - dbus==1.13.18=hb2f20db_0
  - freetype==2.10.4=h5ab3b9f_0
  - libtiff==4.2.0=h85742a9_0
  - scipy==1.6.2=py38had2a1c9_1
  - pillow==8.3.1=py38h2c7a002_0
  - fontconfig==2.13.1=h6c09931_0
  - numexpr==2.7.3=py38h22e1b3c_1
  - matplotlib==3.4.2=py38h06a4308_0
  - pandas==1.3.2=py38h8c16a72_0
  - pip==21.2.2=py38h06a4308_0
  - libgcc-ng==9.3.0=h5101ec6_17
  - mkl==2021.3.0=h06a4308_520
  - ncurses==6.2=he6710b0_1
  - libtasn1==4.16.0=h27cfd23_0
  - lame==3.100=h7b6447c_0
  - openjpeg==2.3.0=h05c96fa_1
  - qt==5.9.7=h5867ecd_1
  - libuv==1.40.0=h7b6447c_0
  - openh264==2.1.0=hd408876_0
  - mkl_random==1.2.2=py38h51133e4_0
  - ffmpeg==4.3=hf484d3e_0
  - libstdcxx-ng==9.3.0=hd4cf53a_17
  - pytorch==1.9.0=py3.8_cuda10.2_cudnn7.6.5_0
  - nettle==3.7.3=hbbd107a_1
  - python==3.8.11=h12debd9_0_cpython
  - numpy-base==1.20.3=py38h74d4b33_0
  - tk==8.6.10=hbc83047_0
  - pyqt==5.9.2=py38h05f1152_4
  - ca-certificates==2021.10.26=h06a4308_2
  - matplotlib-base==3.4.2=py38hab158f2_0
  - gmp==6.2.1=h2531618_2
  - gstreamer==1.14.0=h28cd5cc_2
  - certifi==2021.10.8=py38h06a4308_2
  - bzip2==1.0.8=h7b6447c_0
  - gst-plugins-base==1.14.0=h8213a91_2
  - jpeg==9b=h024ee3a_2
  - bottleneck==1.3.2=py38heb32a55_1
  - setuptools==52.0.0=py38h06a4308_0
  - ld_impl_linux-64==2.35.1=h7274673_9
  - icu==58.2=he6710b0_3

**Comment by xiyelong** [comment]
On November 2nd, 23rd, this issue still existed.

**Comment by MrMello7** [comment]
> 11月2日、23日，该问题依然存在。
I gave up creating an environment under Win10 and instead used a Linux server, which was very easy to create.

**Comment by MrMello7** [comment]
> On November 2nd, 23rd, this issue still existed.
I gave up creating an environment under Win10 and instead used a Linux server, which was very easy to create.
