### ISSUE TITLE
detail of GMFlow+

### ISSUE THREAD

**Issue by zwei-lin** [haofeixu/gmflow#4]
Hi,
  Thanks for the great code!
  I find that there is GMFlow+ on the Sintel benchmark. It says GMFlow+ is a straightforward extention of GMFlow and achieves significant results. Could you give some details about GMFlow+ or the difference between GMFlow+ and GMFlow? Besides, I wonder whether the code of GMFlow+ will be released.
  Thanks!

**Comment by haofeixu** [comment]
Hi, thanks! GMFlow+ is a simple extention built on top of GMFlow. Our original GMFlow paper purses a minimal design for better speed-accuracy trade-off, while GMFlow+ aims to fully unlash GMFlow's potential. The difference is that GMFlow+ uses additional refinements for further improvement. GMFlow+'s code will be released in future, please stay tuned! Thanks!

**Comment by zwei-lin** [comment]
Thank you for your careful reply! Looking forward to the new code.

**Comment by haofeixu** [comment]
Hi @zwei-lin , I have released the GMFlow+ model at https://github.com/autonomousvision/unimatch, and more info about our new work can be found at at https://haofeixu.github.io/unimatch/. Hope it helps, thanks.
