### ISSUE TITLE
Clear Image Failures

### ISSUE THREAD

**Issue by GloryyrolG** [haofeixu/gmflow#42]
Hi @haofeixu @dcharatan et al.,

Thx for ur great contribution. I tried the method but failed in some clear images. E.g.,

![image](https://github.com/haofeixu/gmflow/assets/33202229/53d05e09-de45-48df-871c-f592c3fa829a)

We can see the flow in the BG is not correct though the images are very clear. I suspected this may be cuz, 1. out-of-distribution images, & 2. the motion is a bit large.

Or it can also be accounted for the cornerless background's motion is ambiguous (if it is static or dynamic) so we should not look at it?

Thx & best,

**Comment by haofeixu** [comment]
Hi, it seems that this is a generalization issue. The network doesn't see similar data (with white background) during traininig.
