### ISSUE TITLE
关于标准化图像时的标准差。

### ISSUE THREAD

**Issue by Air1000thsummer** [haofeixu/gmflow#43]
作者大大，您好！
感谢您出色的工作！
我想向您请问一下，再图像输入到模型之后，会进行一次normalize_img()的过程，我想请问一下，在这个标准化中，均值为什么选择是[0.485, 0.456, 0.406]、方差为什么选择[0.229, 0.224, 0.225]？
望得到回复。
感谢。

**Comment by haofeixu** [comment]
Hi 您好，这是 ImageNet 上的 mean 和 variance。
