### ISSUE TITLE
几个问题请教下

### ISSUE THREAD

**Issue by Baiyuetribe** [haofeixu/gmflow#5]
1. 内容看起来很不错，但是实际这个光流法可运用于哪些场景？
2. 能否实现类似补帧的功能？因为从文献推荐看这个比较接近

**Comment by haofeixu** [comment]
可以参考这个视频：https://www.bilibili.com/video/BV18A4y1R7PL，我们对 GMFlow 做的一个不太技术性的介绍，里面提到的光流应用场景有三维重建，运动物体的分割以及你所提到的补帧。

**Comment by Baiyuetribe** [comment]
感谢回复，如有可能，希望代码里新增视频介绍的几个demo最小案例，或许我可以将这些转换成GUI界面。尤其是视频补帧，当然我不擅长模型训练，只是建议。

**Comment by haofeixu** [comment]
很好的建议，感谢！不过我们这个项目主要关注光流本身，对其下游相关的应用目前没有开展。这些应用一般都有单独的项目具体来做，网上也能搜到一些~

**Comment by Baiyuetribe** [comment]
这么说视频演示只是用其他工具生成的，并不是使用本论文提到的方法做到的？感觉很遗憾，我还以为可以对补帧、多帧抠图有效果

**Comment by haofeixu** [comment]
视频是 general 地展示了光流的用途，理论上任何一个光流算法都可以用于下游相关应用 （当然可以将 GMFlow 应用于补帧等任务），只是这些应用不是我们这篇论文的主要关注点，我们关注于光流这个问题本身。
