### ISSUE TITLE
Problem about bidir_flow and inference_size in the code

### ISSUE THREAD

**Issue by RaymondWang987** [haofeixu/gmflow#6]
Hi,
Thanks for releasing your code! 

I find that there might be a bug when i specify the inference_size:

CUDA_VISIBLE_DEVICES=0 python main.py --batch_size 12 --inference_dir /XXX/ --dir_paired_data  --output_path /XXX/ --resume pretrained/gmflow_sintel-0c07dcb3.pth --inference_size 540 960 --pred_bidir_flow 

The error raises:
File "/XXX/evaluate.py", line 662, in inference_on_dir
    flow_bwd = padder.unpad(flow_pr[1]).permute(1, 2, 0).cpu().numpy()  # [H, W, 2]
UnboundLocalError: local variable 'padder' referenced before assignment

It seems that it fails to predict the bidir_flow and the consistency mask when the inference_size is specified.

**Comment by haofeixu** [comment]
Hi, 
Thanks for reporting this issue! It should have been fixed in the latest commit.
