### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by menghuaa** [haofeixu/gmflow#8]
您好，我使用您提供的指令CUDA_VISIBLE_DEVICES=0 python main.py \
--inference_dir demo/sintel_market_1 \
--output_path output/gmflow-norefine-sintel_market_1 \
--resume pretrained/gmflow_sintel-0c07dcb3.pth进行测试，sintel_market_1文件夹是您提供的图片，这个文件夹有三种图片，我删除了一张图片，只留下frame_0001.png和frame_0002.png。这个预测出来的光流，是frame_0001.png到frame_0002.png的光流吗？如果是这样的话，显示出的光流图根据颜色来看好像反了。

**Comment by haofeixu** [comment]
您好，是的，是第一帧到第二帧的光流，颜色是没问题的，我们用的 colormap 是这样的：

![image](https://user-images.githubusercontent.com/19343475/179453922-6486926f-becc-4f61-b8ed-e1df9e087dd3.png)

**Comment by menghuaa** [comment]
> 您好，是的，是第一帧到第二帧的光流，颜色是没问题的，我们用的 colormap 是这样的：
> 
> ![image](https://user-images.githubusercontent.com/19343475/179453922-6486926f-becc-4f61-b8ed-e1df9e087dd3.png)

你好，如果我用frame_0001.png+光流值，理论上会得到frame_0001.png中的像素在frame_0002.png中的位置吗？

**Comment by haofeixu** [comment]
是的

**Comment by menghuaa** [comment]
> 是的

谢谢您
