### ISSUE TITLE
About FlyingThings3D and KITTI 

### ISSUE THREAD

**Issue by klinic** [haofeixu/gmflow#9]
我尊敬的作者，您好：
【1】FlyingThings3D这个数据集，是应该下载这3项吗？
![image](https://user-images.githubusercontent.com/38089696/179645709-093e164c-8f6b-48a6-83ad-cab000718538.png)

【2】KITTI 这个数据集，是下载这3项吗？
![image](https://user-images.githubusercontent.com/38089696/179645842-4c2b90f0-2bb7-4bf2-9a3d-610494666056.png)

期待您的恢复
        敬礼！

**Comment by haofeixu** [comment]
Hi 您好，
[1] 是的
[2] KITTI 只需下载第一个2G的即可
